on: 
  workflow_dispatch: 

jobs: 
  hello_world_job: 
    runs-on: ubuntu-latest 
    name: A job to say hello 
    steps: 
      - uses: actions/checkout@v4 
      - id: foo 
        uses: SashaOrg/Composite/my-composite-action@master
        with:
          who-to-greet: yatsss 
      - run: echo random-number "$RANDOM_NUMBER" 
        shell: bash 
        env: 
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
